In [1]:
from pathlib import Path
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

## Gebäudemodell HN

In [2]:
GPKG_PATH = (
    "1_Rohdaten/HN/HN-Gebäudemodell/"
    "HN-Gebäudemodell_04_08_2026/"
    "260728_Gebäudemodell_HohenNeuendorf.gpkg"
)

In [3]:
gdf = gpd.read_file(GPKG_PATH)

ERROR 1: PROJ: proj_create_from_database: Open of /home/norman/miniconda3/envs/esm-2023/share/proj failed

In [4]:
demand_kwh_ges = gdf["demand_kwh"].sum()*1e-6
print("Wärmeverbrauch über alle Einträge beträgt", round(demand_kwh_ges,2), "GWh")

Wärmeverbrauch über alle Einträge beträgt 213.99 GWh

In [5]:
gdf_with_ID = gdf[~gdf["GebaeudeID"].isna()]
demand_kwh_ID = gdf_with_ID["demand_kwh"].sum()*1e-6
gdf_with_function = gdf[~gdf["funktion"].isna()]
demand_kwh_function = gdf_with_function["demand_kwh"].sum()*1e-6
print("Wärmeverbrauch über alle Gebäude_ID beträgt", round(demand_kwh_ID,2), "GWh")
print("Es gibt",len(gdf_with_ID), "mit Gebaeude_ID")
print("Wärmeverbrauch über alle Gebäude ohne Gebäude_ID und mit funktion beträgt", round(round(demand_kwh_ges,2) - round(demand_kwh_ID,2),2), "GWh")
print("Wärmeverbrauch über alle Gebäude ohne Gebäude_ID und mit funktion beträgt", round(demand_kwh_function,2), "GWh")
print("Es gibt",len(gdf_with_function), "ohne Gebaeude_ID")

Wärmeverbrauch über alle Gebäude_ID beträgt 189.63 GWh
Es gibt 9550 mit Gebaeude_ID
Wärmeverbrauch über alle Gebäude ohne Gebäude_ID und mit funktion beträgt 24.36 GWh
Wärmeverbrauch über alle Gebäude ohne Gebäude_ID und mit funktion beträgt 24.36 GWh
Es gibt 2279 ohne Gebaeude_ID

In [6]:
len(gdf)

11829

In [7]:
len(gdf["geometry"].unique())

11829

In [8]:
gdf_with_function.iloc[1,:]

GebaeudeID                                                       None
StrName                                                          None
Hausnummer                                                        NaN
Stadtteil                                                        None
PLZ                                                              None
Gemeinde                                                         None
AGS                                                               NaN
Landkreis                                                        None
Flur                                                              NaN
Flurstueck                                                       None
Gemarkung                                                        None
BauAltKl                                                     Vor 1919
GebTyp                                                           None
NutzungArt                                                       None
AnzlWhg                                                          None
SolarPot_k                                                        NaN
Waermebed_                                                      11725
ETraeger1                                                         Gas
ETraeger2                                                        None
HzngTec1                                                         None
HzngTec2                                                         None
EndEVer_RW                                                        NaN
EndEVer_kw                                                        NaN
CO2_RW_tco                                                        NaN
CO2_tco2_a                                                        NaN
Datenquali                                                       None
gemeinde_n                                                       None
Etagen                                                              1
funktion                      Nach Quellenlage nicht zu spezifizieren
heating_carrier                                                   GAS
Bedarf_katatster                                              11725.0
Nutzung                                                          None
Baualter_int                                                     1919
komm                                                              NaN
sector                                                              2
demand_kwh                                                      29236
denkmal                                                          None
hoehe_korr                                                        3.0
etagen_fin                                                          1
nutzflaeche_korr                                                   67
P_th                                                               14
demand_spec                                                436.358209
demand_2030                                                     14606
demand_2035                                                     14606
demand_2040                                                     14606
demand_2045                                                     14606
demand_spec_san                                                 218.0
geometry            MULTIPOLYGON (((381955.063 5841230.066, 381956...
Name: 17, dtype: object

In [9]:
len(gdf_with_ID)

9550

In [10]:
gdf_with_funktion = gdf[~gdf["funktion"].isna()]
df = gdf[~gdf["funktion"].isna() & ~gdf["GebaeudeID"].isna()]
print(df)
print("Es gibt keine Gebäude, die ein Funktion und eine Gebäude_ID haben")

Empty GeoDataFrame
Columns: [GebaeudeID, StrName, Hausnummer, Stadtteil, PLZ, Gemeinde, AGS, Landkreis, Flur, Flurstueck, Gemarkung, BauAltKl, GebTyp, NutzungArt, AnzlWhg, SolarPot_k, Waermebed_, ETraeger1, ETraeger2, HzngTec1, HzngTec2, EndEVer_RW, EndEVer_kw, CO2_RW_tco, CO2_tco2_a, Datenquali, gemeinde_n, Etagen, funktion, heating_carrier, Bedarf_katatster, Nutzung, Baualter_int, komm, sector, demand_kwh, denkmal, hoehe_korr, etagen_fin, nutzflaeche_korr, P_th, demand_spec, demand_2030, demand_2035, demand_2040, demand_2045, demand_spec_san, geometry]
Index: []

[0 rows x 48 columns]
Es gibt keine Gebäude, die ein Funktion und eine Gebäude_ID haben

In [11]:
gdf["ETraeger1"].unique()

array(['FesteBiomasse', 'Gas', 'Oel', 'Strom'], dtype=object)

In [12]:
gdf["ETraeger2"].unique()

array([None, 'Feste_Biomasse', 'Solarthermie'], dtype=object)

### Identifier in "funktion", "NutzungArt" und "GebTyp"

In [13]:
print(gdf["funktion"].unique())
print(gdf["funktion"].unique().size)

[None 'Garage' 'Nach Quellenlage nicht zu spezifizieren'
 'Land- und forstwirtschaftliches Betriebsgebäude'
 'Gebäude zur Freizeitgestaltung' 'Überdachung' 'Schuppen'
 'Gebäude für Wirtschaft oder Gewerbe' 'Tiefgarage'
 'Wohngebäude mit Handel und Dienstleistungen' 'Werkstatt' 'Fahrzeughalle'
 'Wohnhaus' 'Sport-, Turnhalle' 'Gebäude zur Elektrizitätsversorgung'
 'Wochenendhaus' 'Stall' 'Gebäude zum Parken'
 'Lagerhalle, Lagerschuppen, Lagerhaus' 'Stellwerk, Blockstelle' 'Kirche'
 'Gebäude für Sportzwecke' 'Gebäude für Vorratshaltung' 'Pumpstation'
 'Gartenhaus' 'Tankstelle' 'Gebäude für religiöse Zwecke'
 'Treibhaus, Gewächshaus' 'Scheune' 'Umformer' 'Sonstiges'
 'Gebäude zur Abfallbehandlung' 'Gebäude zur Versorgungsanlage'
 'Betriebsgebäude für Schienenverkehr' 'Gebäude für Gewerbe und Industrie'
 'Kapelle' 'Einkaufszentrum' 'Heizwerk' 'Produktionsgebäude']
39

In [14]:
print(gdf["NutzungArt"].unique())
print(gdf["NutzungArt"].unique().size)

['Freizeit- und Vergn�gungsst�tte' 'Geb�ude f�r Wirtschaft oder Gewerbe'
 'Wohnheim' 'Wohnhaus' None 'Hotel, Motel, Pension'
 'Geb�ude f�r soziale Zwecke' 'Feuerwehr'
 'Wohngeb�ude mit Gewerbe und Industrie'
 'Wohngeb�ude mit Handel und Dienstleistungen'
 'Geb�ude f�r Bildung und Forschung' 'Wohngeb�ude' 'Forschungsinstitut'
 'Wochenendhaus' 'Kinderkrippe, Kindergarten, Kindertagesst�tte'
 'Allgemein bildende Schule' 'Geb�ude f�r Handel und Dienstleistungen'
 'Verwaltungsgeb�ude' 'Geb�ude f�r Gesundheitswesen'
 'Geb�ude f�r Gewerbe und Industrie mit Wohnen' 'Rathaus' 'B�rogeb�ude'
 'Geb�ude f�r Handel und Dienstleistung mit Wohnen'
 'Geb�ude f�r Bewirtung' 'Geb�ude f�r kulturelle Zwecke'
 'Geb�ude f�r �ffentliche Zwecke'
 'Geb�ude f�r betriebliche Sozialeinrichtung' 'Wohn- und Gesch�ftsgeb�ude'
 'Gastst�tte, Restaurant' 'Produktionsgeb�ude'
 'Wohngeb�ude mit Gemeinbedarf' 'Gesch�ftsgeb�ude'
 'Geb�ude f�r Beherbergung' 'Geb�ude f�r Sicherheit und Ordnung'
 'Empfangsgeb�ude' '�rztehaus, Poliklinik' 'Kaufhaus' 'Betriebsgeb�ude'
 'Polizei' 'Kreditinstitut']
40

In [15]:
print(gdf["GebTyp"].unique())
print(gdf["GebTyp"].unique().size)

['Geb�ude f�r Kultur und Freizeit' 'B�ro-, Verwaltungs- oder Amtsgeb�ude'
 'MFH' 'EFH' None 'GMH'
 'Beherbergungs- oder Unterbringungsgeb�ude, Gastronomie- oder Verpflegungsgeb�ude'
 'Verkehrsgeb�ude' 'Geb�ude f�r Forschung und Hochschullehre' 'RH'
 'Schule, Kindertagesst�tte und sonstiges Betreuungsgeb�ude'
 'Handelsgeb�ude' 'Geb�ude f�r Gesundheit und Pflege'
 'Produktions-, Werkstatt-, Lager- oder Betriebsgeb�ude']
14

In [16]:
gdf_with_funktion = gdf[~gdf["funktion"].isna()]
df = gdf[~gdf["funktion"].isna() & ~gdf["GebTyp"].isna()]
print(df)
print("Es gibt keine Gebäude, die ein Funktion und eine GebTyp haben")

Empty GeoDataFrame
Columns: [GebaeudeID, StrName, Hausnummer, Stadtteil, PLZ, Gemeinde, AGS, Landkreis, Flur, Flurstueck, Gemarkung, BauAltKl, GebTyp, NutzungArt, AnzlWhg, SolarPot_k, Waermebed_, ETraeger1, ETraeger2, HzngTec1, HzngTec2, EndEVer_RW, EndEVer_kw, CO2_RW_tco, CO2_tco2_a, Datenquali, gemeinde_n, Etagen, funktion, heating_carrier, Bedarf_katatster, Nutzung, Baualter_int, komm, sector, demand_kwh, denkmal, hoehe_korr, etagen_fin, nutzflaeche_korr, P_th, demand_spec, demand_2030, demand_2035, demand_2040, demand_2045, demand_spec_san, geometry]
Index: []

[0 rows x 48 columns]
Es gibt keine Gebäude, die ein Funktion und eine GebTyp haben

In [17]:
gdf_without_funktion = gdf[gdf["funktion"].isna()]

In [18]:
gdf_without_funktion[gdf_without_funktion["nutzflaeche_korr"] < 35]

Empty GeoDataFrame
Columns: [GebaeudeID, StrName, Hausnummer, Stadtteil, PLZ, Gemeinde, AGS, Landkreis, Flur, Flurstueck, Gemarkung, BauAltKl, GebTyp, NutzungArt, AnzlWhg, SolarPot_k, Waermebed_, ETraeger1, ETraeger2, HzngTec1, HzngTec2, EndEVer_RW, EndEVer_kw, CO2_RW_tco, CO2_tco2_a, Datenquali, gemeinde_n, Etagen, funktion, heating_carrier, Bedarf_katatster, Nutzung, Baualter_int, komm, sector, demand_kwh, denkmal, hoehe_korr, etagen_fin, nutzflaeche_korr, P_th, demand_spec, demand_2030, demand_2035, demand_2040, demand_2045, demand_spec_san, geometry]
Index: []

[0 rows x 48 columns]

In [19]:
gdf_with_funktion["nutzflaeche_korr"]

8         79
17        67
19        59
22        58
43        85
        ...
11821    360
11824    935
11825    476
11826    476
11827    476
Name: nutzflaeche_korr, Length: 2279, dtype: int32

In [20]:
gdf_with_funktion["Datenquali"]

8        None
17       None
19       None
22       None
43       None
         ...
11821    None
11824    None
11825    None
11826    None
11827    None
Name: Datenquali, Length: 2279, dtype: object

## ALKIS

In [21]:
Alkis_GPKG_PATH = (
    "1_Rohdaten/HN/HN-Gebäudemodell/"
    "HN-Gebäudemodell_04_08_2026/"
    "alkis_EG_HN.gpkg"
)

Alkis_gdf = gpd.read_file(Alkis_GPKG_PATH)

In [22]:
Alkis_gdf.head()

,identifier,oid,aktualit,gebnutzbez,funktion,gfkzshh,rellage,name,anzahlgs,gmdschl,lagebeztxt,geometry
0,urn:adv:oid:DEBBAL010007AF5xBL,DEBBAL010007AF5xBL,2013-11-18Z,Gebäude,Garage,31001_2463,None,None,1.0,12065144,None,"MULTIPOLYGON (((381288.558 5837904.589, 381288..."
1,urn:adv:oid:DEBBAL010007AkpIBL,DEBBAL010007AkpIBL,2013-11-13Z,Gebäude,Gebäude für Wirtschaft oder Gewerbe,31001_2000,None,None,NaN,12065144,None,"MULTIPOLYGON (((384886.546 5837191.671, 384886..."
2,urn:adv:oid:DEBBAL010007AkpJBL,DEBBAL010007AkpJBL,2013-11-13Z,Gebäude,Gebäude für Wirtschaft oder Gewerbe,31001_2000,None,None,NaN,12065144,None,"MULTIPOLYGON (((384886.858 5837189.2, 384886.9..."
3,urn:adv:oid:DEBBAL010007CalSBL,DEBBAL010007CalSBL,2013-11-28Z,Gebäude,Wohnhaus,31001_1010,None,None,2.0,12065036,Kleiststraße 31,"MULTIPOLYGON (((384308.261 5838595.856, 384303..."
4,urn:adv:oid:DEBBAL010007Cm6EBL,DEBBAL010007Cm6EBL,2013-11-29Z,Gebäude,Wohnhaus,31001_1010,None,None,1.0,12065144,None,"MULTIPOLYGON (((384065.173 5836619.284, 384066..."

In [23]:
Alkis_gdf.columns

Index(['identifier', 'oid', 'aktualit', 'gebnutzbez', 'funktion', 'gfkzshh',
       'rellage', 'name', 'anzahlgs', 'gmdschl', 'lagebeztxt', 'geometry'],
      dtype='object')

In [24]:
Alkis_gdf["funktion"].unique()

array(['Garage', 'Gebäude für Wirtschaft oder Gewerbe', 'Wohnhaus',
       'Lagerhalle, Lagerschuppen, Lagerhaus', 'Gartenhaus', 'Schuppen',
       'Kinderkrippe, Kindergarten, Kindertagesstätte', 'Umformer',
       'Wohngebäude', 'Freizeit- und Vergnügungsstätte',
       'Gebäude für Vorratshaltung', 'Stall', 'Wochenendhaus',
       'Gebäude für religiöse Zwecke', 'Gebäude für soziale Zwecke',
       'Gebäude für Sportzwecke',
       'Gebäude für Handel und Dienstleistungen',
       'Wohn- und Geschäftsgebäude', 'Gebäude zur Freizeitgestaltung',
       'Bürogebäude', 'Werkstatt', 'Gebäude für Gewerbe und Industrie',
       'Geschäftsgebäude', 'Wohngebäude mit Handel und Dienstleistungen',
       'Gebäude für Gesundheitswesen', 'Sport-, Turnhalle',
       'Wohngebäude mit Gewerbe und Industrie',
       'Gebäude zur Elektrizitätsversorgung',
       'Gebäude für Handel und Dienstleistung mit Wohnen',
       'Wohngebäude mit Gemeinbedarf', 'Gebäude zur Versorgungsanlage',
       'Nach Quellenlage nicht zu spezifizieren',
       'Gebäude für Erholungszwecke', 'Fahrzeughalle', 'Scheune',
       'Allgemein bildende Schule', 'Gaststätte, Restaurant', 'Rathaus',
       'Land- und forstwirtschaftliches Betriebsgebäude',
       'Einkaufszentrum', 'Feuerwehr', 'Gebäude für Bewirtung',
       'Gebäude zur Gasversorgung', 'Gebäude zum Parken',
       'Gebäude für Bildung und Forschung', 'Produktionsgebäude',
       'Betriebsgebäude', 'Gebäude für betriebliche Sozialeinrichtung',
       'Museum', 'Hütte (ohne Übernachtungsmöglichkeit)',
       'Treibhaus, Gewächshaus', 'Kirche', 'Versicherung',
       'Gebäude für Sicherheit und Ordnung',
       'Betriebsgebäude für Schienenverkehr', 'Kaufhaus',
       'Ärztehaus, Poliklinik', 'Kapelle',
       'Gebäude für Gewerbe und Industrie mit Wohnen',
       'Hotel, Motel, Pension', 'Gebäude für Beherbergung', 'Krankenhaus',
       'Wohnheim', 'Empfangsgebäude', 'Gebäude für kulturelle Zwecke',
       'Heizwerk', 'Gebäude zur Wasserversorgung',
       'Betriebsgebäude für Schiffsverkehr', 'Pumpstation',
       'Gebäude für andere Erholungseinrichtung',
       'Gebäude für öffentliche Zwecke', 'Polizei', 'Kreditinstitut',
       'Tankstelle', 'Gebäude zur Abwasserbeseitigung',
       'Forschungsinstitut', 'Betriebsgebäude für Straßenverkehr',
       'Stellwerk, Blockstelle', 'Friedhofsgebäude',
       'Gebäude für Fernmeldewesen', 'Verwaltungsgebäude',
       'Gebäude zur Abfallbehandlung', 'Durchfahrt im Gebäude',
       'Tiefgarage', 'Überdachung', 'Kran', 'Sonstiges',
       'Sende-, Funkturm, Fernmeldeturm', 'Schornstein', 'Aussichtsturm',
       'Parkhaus', 'Abweichende Geschosshöhe', 'Funkmast',
       'Auskragender Geschossteil / zurückspringendes Geschoss', 'Keller'],
      dtype=object)

## Wärmekatastar

In [25]:
WK_GPKG_PATH = (
    "1_Rohdaten/HN/HN-Gebäudemodell/"
    "HN-Gebäudemodell_04_08_2026/"
    "WK_EG_HN.gpkg"
)

WK_gdf = gpd.read_file(WK_GPKG_PATH)

In [26]:
WK_gdf.columns

Index(['GebaeudeID', 'StrName', 'Hausnummer', 'Stadtteil', 'PLZ', 'Gemeinde',
       'AGS', 'Landkreis', 'Flur', 'Flurstueck', 'Gemarkung', 'GrundFl_qm',
       'BruGeschFl_qm', 'BauAltKl', 'GebTyp', 'NutzungArt', 'AnzlWhg',
       'SolarPot_kwh_a', 'Waermebed_kwh_a', 'ETraeger1', 'ETraeger2',
       'HzngTec1', 'HzngTec2', 'EndEVer_RW_kwh_a', 'EndEVer_kwh_a',
       'CO2_RW_tco2_a', 'CO2_tco2_a', 'Datenqualitaet', 'gemeinde_name',
       'geometry'],
      dtype='object')

In [27]:
WK_gdf["NutzungArt"].unique()

array(['Wohnhaus', 'Kinderkrippe, Kindergarten, Kindertagesstätte',
       'Wohngebäude', 'Freizeit- und Vergnügungsstätte',
       'Gebäude für Wirtschaft oder Gewerbe',
       'Gebäude für soziale Zwecke',
       'Gebäude für Handel und Dienstleistungen', 'Bürogebäude',
       'Geschäftsgebäude', 'Wohngebäude mit Handel und Dienstleistungen',
       'Gebäude für Gesundheitswesen', 'Wochenendhaus',
       'Gebäude für Handel und Dienstleistung mit Wohnen',
       'Wohn- und Geschäftsgebäude', 'Allgemein bildende Schule',
       'Rathaus', 'Wohngebäude mit Gemeinbedarf',
       'Wohngebäude mit Gewerbe und Industrie',
       'Gebäude für Sicherheit und Ordnung', 'Feuerwehr', 'Kaufhaus',
       'Ärztehaus, Poliklinik',
       'Gebäude für Gewerbe und Industrie mit Wohnen',
       'Hotel, Motel, Pension', 'Betriebsgebäude',
       'Gebäude für Beherbergung', 'Produktionsgebäude',
       'Gebäude für Erholungszwecke', 'Empfangsgebäude',
       'Einkaufszentrum', 'Gebäude für öffentliche Zwecke',
       'Gebäude für Bewirtung', 'Verwaltungsgebäude', 'Polizei',
       'Kreditinstitut', 'Wohnheim', 'Gebäude für Bildung und Forschung',
       'Forschungsinstitut', 'Gebäude für kulturelle Zwecke',
       'Gaststätte, Restaurant',
       'Gebäude für betriebliche Sozialeinrichtung', 'Krankenhaus',
       'Gebäude für Gewerbe und Industrie'], dtype=object)

In [28]:
gdf.columns

Index(['GebaeudeID', 'StrName', 'Hausnummer', 'Stadtteil', 'PLZ', 'Gemeinde',
       'AGS', 'Landkreis', 'Flur', 'Flurstueck', 'Gemarkung', 'BauAltKl',
       'GebTyp', 'NutzungArt', 'AnzlWhg', 'SolarPot_k', 'Waermebed_',
       'ETraeger1', 'ETraeger2', 'HzngTec1', 'HzngTec2', 'EndEVer_RW',
       'EndEVer_kw', 'CO2_RW_tco', 'CO2_tco2_a', 'Datenquali', 'gemeinde_n',
       'Etagen', 'funktion', 'heating_carrier', 'Bedarf_katatster', 'Nutzung',
       'Baualter_int', 'komm', 'sector', 'demand_kwh', 'denkmal', 'hoehe_korr',
       'etagen_fin', 'nutzflaeche_korr', 'P_th', 'demand_spec', 'demand_2030',
       'demand_2035', 'demand_2040', 'demand_2045', 'demand_spec_san',
       'geometry'],
      dtype='object')

In [29]:
Alkis_gdf.columns

Index(['identifier', 'oid', 'aktualit', 'gebnutzbez', 'funktion', 'gfkzshh',
       'rellage', 'name', 'anzahlgs', 'gmdschl', 'lagebeztxt', 'geometry'],
      dtype='object')

In [30]:
WK_gdf.columns

Index(['GebaeudeID', 'StrName', 'Hausnummer', 'Stadtteil', 'PLZ', 'Gemeinde',
       'AGS', 'Landkreis', 'Flur', 'Flurstueck', 'Gemarkung', 'GrundFl_qm',
       'BruGeschFl_qm', 'BauAltKl', 'GebTyp', 'NutzungArt', 'AnzlWhg',
       'SolarPot_kwh_a', 'Waermebed_kwh_a', 'ETraeger1', 'ETraeger2',
       'HzngTec1', 'HzngTec2', 'EndEVer_RW_kwh_a', 'EndEVer_kwh_a',
       'CO2_RW_tco2_a', 'CO2_tco2_a', 'Datenqualitaet', 'gemeinde_name',
       'geometry'],
      dtype='object')

## prepared DF

In [32]:
GPKG_PATH = (
    "outputs/gebaeudemodell/prepared/gebaeudemodell_prepared.gpkg"
)
gdf_prepared = gpd.read_file(GPKG_PATH)

In [39]:
gdf_umformer = gdf_prepared[gdf_prepared["NutzungArt_und_funktion"] == "Umformer"]
gdf_umformer["geometry"]

3651     MULTIPOLYGON (((381787.74 5838058.02, 381781.2...
6090     MULTIPOLYGON (((382123.394 5835986.494, 382129...
6167     MULTIPOLYGON (((381361.843 5834048.395, 381362...
8007     MULTIPOLYGON (((381649.927 5842214.401, 381657...
9634     MULTIPOLYGON (((383922.688 5834469.152, 383936...
10424    MULTIPOLYGON (((383441.78 5844706.16, 383449.9...
Name: geometry, dtype: geometry

In [42]:
gdf_prepared[gdf_prepared["NutzungArt_und_funktion"] == "Wohngebäude"]["GebTyp"]

106      EFH
355      EFH
648      EFH
944      EFH
1554     MFH
1890     EFH
2543     EFH
3511     EFH
3775     EFH
4858     EFH
5185     EFH
5267     EFH
5337     EFH
7977     EFH
10105    EFH
11161    EFH
Name: GebTyp, dtype: object

In [44]:
gdf_prepared[gdf_prepared["NutzungArt_und_funktion"] == "Wohnheim"]["GebTyp"]

3        MFH
431      MFH
548      MFH
1113     MFH
2296     MFH
5428     GMH
6564     EFH
7997     GMH
8004     GMH
8970     GMH
10546    MFH
Name: GebTyp, dtype: object

In [45]:
gdf_prepared[gdf_prepared["NutzungArt_und_funktion"] == "Gebäude für Gewerbe und Industrie mit Wohnen"]["GebTyp"]

2130     MFH
11774    EFH
Name: GebTyp, dtype: object

In [46]:
gdf_prepared[gdf_prepared["NutzungArt_und_funktion"] == "Betriebsgebäude"]

,GebaeudeID,StrName,Hausnummer,Stadtteil,PLZ,Gemeinde,AGS,Landkreis,Flur,Flurstueck,...,P_th,demand_spec,demand_2030,demand_2035,demand_2040,demand_2045,demand_spec_san,Quelle,NutzungArt_und_funktion,geometry
11147,DEBBAL650002lB7zBL,Gewerbestra�e,16.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,137,...,1,27.714286,2716,2716,2716,2716,27.714286,WK,Betriebsgebäude,"MULTIPOLYGON (((384586.594 5835831.03, 384587...."
11544,DEBBAL650002lB7eBL,Gewerbestra�e,12.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,123,...,2,19.578059,4640,4640,4640,4640,19.578059,WK,Betriebsgebäude,"MULTIPOLYGON (((384478.299 5835845.954, 384479..."
11546,DEBBAL650002lB7bBL,Gewerbestra�e,12.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,123,...,6,19.535235,11643,11643,11643,11643,19.535235,WK,Betriebsgebäude,"MULTIPOLYGON (((384494.96 5835850.42, 384479.8..."
11711,DEBBAL650003yVUHBL,Scharfschwerdtstra�e,47.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,8.0,266,...,2,14.376471,3666,3666,3666,3666,14.376471,WK,Betriebsgebäude,"MULTIPOLYGON (((383771.001 5836384.86, 383755...."
11726,DEBBAL650002lB6VBL,Gewerbestra�e,31.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,104,...,2,13.843373,3447,3447,3447,3447,13.843373,WK,Betriebsgebäude,"MULTIPOLYGON (((384390.52 5835942.865, 384389...."
11728,DEBBAL650002lB7tBL,Parkstra�e,19.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,96,...,0,13.785714,772,772,772,772,13.785714,WK,Betriebsgebäude,"MULTIPOLYGON (((384555.129 5835962.592, 384565..."
11730,DEBBAL650002lzwMBL,Uhlandstra�e,2.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,2.0,1837,...,0,13.735849,728,728,728,728,13.735849,WK,Betriebsgebäude,"MULTIPOLYGON (((386154.35 5836927.997, 386160...."
11766,DEBBAL650002lB7kBL,Gewerbestra�e,13.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,154,...,1,10.963415,1798,1798,1798,1798,10.963415,WK,Betriebsgebäude,"MULTIPOLYGON (((384503.508 5835847.386, 384505..."
11791,DEBBAL650002lB7PBL,Parkstra�e,10.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,210,...,0,8.435897,987,987,987,987,8.435897,WK,Betriebsgebäude,"MULTIPOLYGON (((384323.795 5836022.958, 384338..."
11828,DEBBAL650002lB6XBL,Gewerbestra�e,9.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,120,...,0,0.953488,533,533,533,533,0.953488,WK,Betriebsgebäude,"MULTIPOLYGON (((384385.986 5835855.09, 384373...."