In [3]:
from pathlib import Path
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

In [4]:
GPKG_PATH = (
    "1_Rohdaten/HN/HN-Gebäudemodell/"
    "HN-Gebäudemodell_04_08_2026/"
    "260728_Gebäudemodell_HohenNeuendorf.gpkg"
)

In [6]:
gdf = gpd.read_file(GPKG_PATH)
gdf

,GebaeudeID,StrName,Hausnummer,Stadtteil,PLZ,Gemeinde,AGS,Landkreis,Flur,Flurstueck,...,etagen_fin,nutzflaeche_korr,P_th,demand_spec,demand_2030,demand_2035,demand_2040,demand_2045,demand_spec_san,geometry
0,DEBBAL650003yUOMBL,Sch�nflie�er Stra�e,17.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,25. Feb,...,1,194,193,2089.221649,202730,202730,202730,202730,1045.000000,"MULTIPOLYGON (((384221.774 5836832.742, 384228..."
1,DEBBAL650002DwVCBL,Feuerdornweg,17.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,33/65,...,1,63,41,1380.142857,43470,43470,43470,43470,690.000000,"MULTIPOLYGON (((383034.995 5841956.586, 383027..."
2,DEBBAL650002DwVQBL,Feuerdornweg,2.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,33/52,...,1,40,19,987.700000,19760,19760,19760,19760,494.000000,"MULTIPOLYGON (((383005.96 5841839.97, 383006.8..."
3,DEBBAL650003yVTXBL,Scharfschwerdtstra�e,44.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,8.0,549,...,3,475,174,769.541053,182875,182875,182875,182875,385.000000,"MULTIPOLYGON (((383692.53 5836350.012, 383694...."
4,DEBBAL650003yUeEBL,Waldstra�e,11.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,2.0,31,...,1,83,30,767.879518,31872,31872,31872,31872,384.000000,"MULTIPOLYGON (((384478.174 5837340.642, 384479..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11824,None,None,NaN,None,None,None,NaN,None,NaN,None,...,3,935,1,2.117647,1980,1980,1980,1980,2.117647,"MULTIPOLYGON (((382431.263 5836222.876, 382435..."
11825,None,None,NaN,None,None,None,NaN,None,NaN,None,...,2,476,0,1.783613,849,849,849,849,1.783613,"MULTIPOLYGON (((381123.964 5837475.488, 381138..."
11826,None,None,NaN,None,None,None,NaN,None,NaN,None,...,2,476,0,1.783613,849,849,849,849,1.783613,"MULTIPOLYGON (((381096.792 5837483.84, 381111...."
11827,None,None,NaN,None,None,None,NaN,None,NaN,None,...,2,476,0,1.783613,849,849,849,849,1.783613,"MULTIPOLYGON (((381104.406 5837508.624, 381119..."
11828,DEBBAL650002lB6XBL,Gewerbestra�e,9.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,120,...,2,559,0,0.953488,533,533,533,533,0.953488,"MULTIPOLYGON (((384385.986 5835855.09, 384373...."

In [46]:
demand_kwh_ges = gdf["demand_kwh"].sum()*1e-6
print("Wärmeverbrauch über alle Einträge beträgt", round(demand_kwh_ges,2), "GWh")

Wärmeverbrauch über alle Einträge beträgt 213.99 GWh

In [45]:
gdf_with_ID = gdf[~gdf["GebaeudeID"].isna()]
demand_kwh_ID = gdf_with_ID["demand_kwh"].sum()*1e-6
print("Wärmeverbrauch über alle Gebäude_ID beträgt", round(demand_kwh_ID,2), "GWh")

Wärmeverbrauch über alle Gebäude_ID beträgt 189.63 GWh

In [37]:
gdf_with_funktion = gdf[~gdf["funktion"].isna()]
df = gdf[~gdf["funktion"].isna() & ~gdf["GebaeudeID"].isna()]
print(df)
print("Es gibt keine Gebäude, die ein Funktion und eine Gebäude_ID haben")

Empty GeoDataFrame
Columns: [GebaeudeID, StrName, Hausnummer, Stadtteil, PLZ, Gemeinde, AGS, Landkreis, Flur, Flurstueck, Gemarkung, BauAltKl, GebTyp, NutzungArt, AnzlWhg, SolarPot_k, Waermebed_, ETraeger1, ETraeger2, HzngTec1, HzngTec2, EndEVer_RW, EndEVer_kw, CO2_RW_tco, CO2_tco2_a, Datenquali, gemeinde_n, Etagen, funktion, heating_carrier, Bedarf_katatster, Nutzung, Baualter_int, komm, sector, demand_kwh, denkmal, hoehe_korr, etagen_fin, nutzflaeche_korr, P_th, demand_spec, demand_2030, demand_2035, demand_2040, demand_2045, demand_spec_san, geometry]
Index: []

[0 rows x 48 columns]
Es gibt keine Gebäude, die ein Funktion und eine Gebäude_ID haben

In [39]:
gdf["ETraeger1"].unique()

array(['FesteBiomasse', 'Gas', 'Oel', 'Strom'], dtype=object)

In [40]:
gdf["ETraeger2"].unique()

array([None, 'Feste_Biomasse', 'Solarthermie'], dtype=object)

In [41]:
gdf["HzngTec1"].unique()

array(['Pelletkessel', 'Gaskessel', '�lkessel', 'Gasetagenheizung', None,
       'W�rmepumpe (Strom)', 'Nachtspeicher'], dtype=object)

In [42]:
gdf["HzngTec2"].unique()

array(['none', 'nan', None, 'Kamin (Bestand)', 'Solarthermie (Bestand)'],
      dtype=object)

In [43]:
gdf[gdf["HzngTec1"] == 'W�rmepumpe (Strom)']

,GebaeudeID,StrName,Hausnummer,Stadtteil,PLZ,Gemeinde,AGS,Landkreis,Flur,Flurstueck,...,etagen_fin,nutzflaeche_korr,P_th,demand_spec,demand_2030,demand_2035,demand_2040,demand_2045,demand_spec_san,geometry
64,DEBBAL650003yTu5BL,Waldstra�e,30.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,1.0,1623,...,1,338,47,290.263314,49010,49010,49010,49010,145.000000,"MULTIPOLYGON (((384769.534 5837457.968, 384775..."
65,DEBBAL010008SHmWBL,Oranienburger Stra�e,27.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,1.0,890/2,...,2,190,26,289.994737,27550,27550,27550,27550,145.000000,"MULTIPOLYGON (((383928.301 5838503.951, 383939..."
72,DEBBAL01000bRpZdBL,Z�hlsdorfer Stra�e,32.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,1.0,2296,...,1,193,26,280.963731,27020,27020,27020,27020,140.000000,"MULTIPOLYGON (((383966.278 5838296.037, 383951..."
76,DEBBAL650003yUjhBL,An den Rotpfuhlen,34.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,2.0,193,...,1,101,13,276.693069,13938,13938,13938,13938,138.000000,"MULTIPOLYGON (((384971.736 5837024.49, 384975...."
78,DEBBAL650003yUwBBL,L�rchenweg,3.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,4.0,236/4,...,2,409,54,276.293399,56442,56442,56442,56442,138.000000,"MULTIPOLYGON (((384718.911 5836537.664, 384738..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11678,DEBBAL650003yTn1BL,Kiefernallee,3.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,1.0,1158/2,...,1,40,0,15.900000,636,636,636,636,15.900000,"MULTIPOLYGON (((384198.717 5837942.668, 384198..."
11716,DEBBAL650002DvvwBL,Nelkenstra�e,14.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,1.0,2151/14,...,2,225,2,14.066667,3165,3165,3165,3165,14.066667,"MULTIPOLYGON (((383394.403 5841744.735, 383396..."
11725,DEBBAL650002DvlaBL,Berliner Chaussee,5.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,1.0,766,...,1,95,1,13.863158,1317,1317,1317,1317,13.863158,"MULTIPOLYGON (((383106.604 5840959.762, 383106..."
11807,DEBBAL650003yUOsBL,Sch�nflie�er Stra�e,637.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,637,...,1,886,2,5.643341,5000,5000,5000,5000,5.643341,"MULTIPOLYGON (((384164.814 5836794.199, 384171..."
11822,DEBBAL650002lB6TBL,Gewerbestra�e,8.0,None,None,Hohen Neuendorf,12065144.0,Oberhavel,5.0,119,...,2,398,1,2.846734,1133,1133,1133,1133,2.846734,"MULTIPOLYGON (((384362.689 5835888.899, 384346..."