In [18]:
from pathlib import Path
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

## Gebäudemodell HN

In [19]:
GPKG_PATH = (
    "1_Rohdaten/HN/HN-Gebäudemodell/"
    "HN-Gebäudemodell_04_08_2026/"
    "260728_Gebäudemodell_HohenNeuendorf.gpkg"
)

In [20]:
gdf = gpd.read_file(GPKG_PATH)

In [21]:
demand_kwh_ges = gdf["demand_kwh"].sum()*1e-6
print("Wärmeverbrauch über alle Einträge beträgt", round(demand_kwh_ges,2), "GWh")

Wärmeverbrauch über alle Einträge beträgt 213.99 GWh

In [22]:
gdf_with_ID = gdf[~gdf["GebaeudeID"].isna()]
demand_kwh_ID = gdf_with_ID["demand_kwh"].sum()*1e-6
gdf_with_function = gdf[~gdf["funktion"].isna()]
demand_kwh_function = gdf_with_function["demand_kwh"].sum()*1e-6
print("Wärmeverbrauch über alle Gebäude_ID beträgt", round(demand_kwh_ID,2), "GWh")
print("Es gibt",len(gdf_with_ID), "mit Gebaeude_ID")
print("Wärmeverbrauch über alle Gebäude ohne Gebäude_ID und mit funktion beträgt", round(round(demand_kwh_ges,2) - round(demand_kwh_ID,2),2), "GWh")
print("Wärmeverbrauch über alle Gebäude ohne Gebäude_ID und mit funktion beträgt", round(demand_kwh_function,2), "GWh")
print("Es gibt",len(gdf_with_function), "ohne Gebaeude_ID")

Wärmeverbrauch über alle Gebäude_ID beträgt 189.63 GWh
Es gibt 9550 mit Gebaeude_ID
Wärmeverbrauch über alle Gebäude ohne Gebäude_ID und mit funktion beträgt 24.36 GWh
Wärmeverbrauch über alle Gebäude ohne Gebäude_ID und mit funktion beträgt 24.36 GWh
Es gibt 2279 ohne Gebaeude_ID

In [23]:
len(gdf_with_ID)

9550

In [24]:
gdf_with_funktion = gdf[~gdf["funktion"].isna()]
df = gdf[~gdf["funktion"].isna() & ~gdf["GebaeudeID"].isna()]
print(df)
print("Es gibt keine Gebäude, die ein Funktion und eine Gebäude_ID haben")

Empty GeoDataFrame
Columns: [GebaeudeID, StrName, Hausnummer, Stadtteil, PLZ, Gemeinde, AGS, Landkreis, Flur, Flurstueck, Gemarkung, BauAltKl, GebTyp, NutzungArt, AnzlWhg, SolarPot_k, Waermebed_, ETraeger1, ETraeger2, HzngTec1, HzngTec2, EndEVer_RW, EndEVer_kw, CO2_RW_tco, CO2_tco2_a, Datenquali, gemeinde_n, Etagen, funktion, heating_carrier, Bedarf_katatster, Nutzung, Baualter_int, komm, sector, demand_kwh, denkmal, hoehe_korr, etagen_fin, nutzflaeche_korr, P_th, demand_spec, demand_2030, demand_2035, demand_2040, demand_2045, demand_spec_san, geometry]
Index: []

[0 rows x 48 columns]
Es gibt keine Gebäude, die ein Funktion und eine Gebäude_ID haben

In [25]:
gdf["ETraeger1"].unique()

array(['FesteBiomasse', 'Gas', 'Oel', 'Strom'], dtype=object)

In [26]:
gdf["ETraeger2"].unique()

array([None, 'Feste_Biomasse', 'Solarthermie'], dtype=object)

### Identifier in "funktion", "NutzungArt" und "GebTyp"

In [27]:
print(gdf["funktion"].unique())
print(gdf["funktion"].unique().size)

[None 'Garage' 'Nach Quellenlage nicht zu spezifizieren'
 'Land- und forstwirtschaftliches Betriebsgebäude'
 'Gebäude zur Freizeitgestaltung' 'Überdachung' 'Schuppen'
 'Gebäude für Wirtschaft oder Gewerbe' 'Tiefgarage'
 'Wohngebäude mit Handel und Dienstleistungen' 'Werkstatt' 'Fahrzeughalle'
 'Wohnhaus' 'Sport-, Turnhalle' 'Gebäude zur Elektrizitätsversorgung'
 'Wochenendhaus' 'Stall' 'Gebäude zum Parken'
 'Lagerhalle, Lagerschuppen, Lagerhaus' 'Stellwerk, Blockstelle' 'Kirche'
 'Gebäude für Sportzwecke' 'Gebäude für Vorratshaltung' 'Pumpstation'
 'Gartenhaus' 'Tankstelle' 'Gebäude für religiöse Zwecke'
 'Treibhaus, Gewächshaus' 'Scheune' 'Umformer' 'Sonstiges'
 'Gebäude zur Abfallbehandlung' 'Gebäude zur Versorgungsanlage'
 'Betriebsgebäude für Schienenverkehr' 'Gebäude für Gewerbe und Industrie'
 'Kapelle' 'Einkaufszentrum' 'Heizwerk' 'Produktionsgebäude']
39

In [28]:
print(gdf["NutzungArt"].unique())
print(gdf["NutzungArt"].unique().size)

['Freizeit- und Vergn�gungsst�tte' 'Geb�ude f�r Wirtschaft oder Gewerbe'
 'Wohnheim' 'Wohnhaus' None 'Hotel, Motel, Pension'
 'Geb�ude f�r soziale Zwecke' 'Feuerwehr'
 'Wohngeb�ude mit Gewerbe und Industrie'
 'Wohngeb�ude mit Handel und Dienstleistungen'
 'Geb�ude f�r Bildung und Forschung' 'Wohngeb�ude' 'Forschungsinstitut'
 'Wochenendhaus' 'Kinderkrippe, Kindergarten, Kindertagesst�tte'
 'Allgemein bildende Schule' 'Geb�ude f�r Handel und Dienstleistungen'
 'Verwaltungsgeb�ude' 'Geb�ude f�r Gesundheitswesen'
 'Geb�ude f�r Gewerbe und Industrie mit Wohnen' 'Rathaus' 'B�rogeb�ude'
 'Geb�ude f�r Handel und Dienstleistung mit Wohnen'
 'Geb�ude f�r Bewirtung' 'Geb�ude f�r kulturelle Zwecke'
 'Geb�ude f�r �ffentliche Zwecke'
 'Geb�ude f�r betriebliche Sozialeinrichtung' 'Wohn- und Gesch�ftsgeb�ude'
 'Gastst�tte, Restaurant' 'Produktionsgeb�ude'
 'Wohngeb�ude mit Gemeinbedarf' 'Gesch�ftsgeb�ude'
 'Geb�ude f�r Beherbergung' 'Geb�ude f�r Sicherheit und Ordnung'
 'Empfangsgeb�ude' '�rztehaus, Poliklinik' 'Kaufhaus' 'Betriebsgeb�ude'
 'Polizei' 'Kreditinstitut']
40

In [29]:
print(gdf["GebTyp"].unique())
print(gdf["GebTyp"].unique().size)

['Geb�ude f�r Kultur und Freizeit' 'B�ro-, Verwaltungs- oder Amtsgeb�ude'
 'MFH' 'EFH' None 'GMH'
 'Beherbergungs- oder Unterbringungsgeb�ude, Gastronomie- oder Verpflegungsgeb�ude'
 'Verkehrsgeb�ude' 'Geb�ude f�r Forschung und Hochschullehre' 'RH'
 'Schule, Kindertagesst�tte und sonstiges Betreuungsgeb�ude'
 'Handelsgeb�ude' 'Geb�ude f�r Gesundheit und Pflege'
 'Produktions-, Werkstatt-, Lager- oder Betriebsgeb�ude']
14

In [30]:
gdf_with_funktion = gdf[~gdf["funktion"].isna()]
df = gdf[~gdf["funktion"].isna() & ~gdf["GebTyp"].isna()]
print(df)
print("Es gibt keine Gebäude, die ein Funktion und eine GebTyp haben")

Empty GeoDataFrame
Columns: [GebaeudeID, StrName, Hausnummer, Stadtteil, PLZ, Gemeinde, AGS, Landkreis, Flur, Flurstueck, Gemarkung, BauAltKl, GebTyp, NutzungArt, AnzlWhg, SolarPot_k, Waermebed_, ETraeger1, ETraeger2, HzngTec1, HzngTec2, EndEVer_RW, EndEVer_kw, CO2_RW_tco, CO2_tco2_a, Datenquali, gemeinde_n, Etagen, funktion, heating_carrier, Bedarf_katatster, Nutzung, Baualter_int, komm, sector, demand_kwh, denkmal, hoehe_korr, etagen_fin, nutzflaeche_korr, P_th, demand_spec, demand_2030, demand_2035, demand_2040, demand_2045, demand_spec_san, geometry]
Index: []

[0 rows x 48 columns]
Es gibt keine Gebäude, die ein Funktion und eine GebTyp haben

In [31]:
#gdf[~gdf["GebTyp"].isna()]

## ALKIS

In [32]:
Alkis_GPKG_PATH = (
    "1_Rohdaten/HN/HN-Gebäudemodell/"
    "HN-Gebäudemodell_04_08_2026/"
    "alkis_EG_HN.gpkg"
)

Alkis_gdf = gpd.read_file(Alkis_GPKG_PATH)

In [33]:
Alkis_gdf.columns

Index(['identifier', 'oid', 'aktualit', 'gebnutzbez', 'funktion', 'gfkzshh',
       'rellage', 'name', 'anzahlgs', 'gmdschl', 'lagebeztxt', 'geometry'],
      dtype='object')

In [35]:
Alkis_gdf

,identifier,oid,aktualit,gebnutzbez,funktion,gfkzshh,rellage,name,anzahlgs,gmdschl,lagebeztxt,geometry
0,urn:adv:oid:DEBBAL010007AF5xBL,DEBBAL010007AF5xBL,2013-11-18Z,Gebäude,Garage,31001_2463,None,None,1.0,12065144,None,"MULTIPOLYGON (((381288.558 5837904.589, 381288..."
1,urn:adv:oid:DEBBAL010007AkpIBL,DEBBAL010007AkpIBL,2013-11-13Z,Gebäude,Gebäude für Wirtschaft oder Gewerbe,31001_2000,None,None,NaN,12065144,None,"MULTIPOLYGON (((384886.546 5837191.671, 384886..."
2,urn:adv:oid:DEBBAL010007AkpJBL,DEBBAL010007AkpJBL,2013-11-13Z,Gebäude,Gebäude für Wirtschaft oder Gewerbe,31001_2000,None,None,NaN,12065144,None,"MULTIPOLYGON (((384886.858 5837189.2, 384886.9..."
3,urn:adv:oid:DEBBAL010007CalSBL,DEBBAL010007CalSBL,2013-11-28Z,Gebäude,Wohnhaus,31001_1010,None,None,2.0,12065036,Kleiststraße 31,"MULTIPOLYGON (((384308.261 5838595.856, 384303..."
4,urn:adv:oid:DEBBAL010007Cm6EBL,DEBBAL010007Cm6EBL,2013-11-29Z,Gebäude,Wohnhaus,31001_1010,None,None,1.0,12065144,None,"MULTIPOLYGON (((384065.173 5836619.284, 384066..."
...,...,...,...,...,...,...,...,...,...,...,...,...
35279,urn:adv:oid:DEBBAL01000doQvRBL,DEBBAL01000doQvRBL,2026-09-15Z,Gebäude,Wohnhaus,31001_1010,None,None,2.0,12065144,None,"MULTIPOLYGON (((382750.004 5837182.637, 382759..."
35280,urn:adv:oid:DEBBAL01000doQvTBL,DEBBAL01000doQvTBL,2026-09-15Z,Gebäude,Wohnhaus,31001_1010,None,None,2.0,12065144,None,"MULTIPOLYGON (((382728.404 5837206.29, 382738...."
35281,urn:adv:oid:DEBBAL01000doQvVBL,DEBBAL01000doQvVBL,2026-09-15Z,Gebäude,Wohnhaus,31001_1010,None,None,2.0,12065144,None,"MULTIPOLYGON (((382715.962 5837185.958, 382725..."
35282,urn:adv:oid:DEBBAL01000doQvXBL,DEBBAL01000doQvXBL,2026-09-15Z,Gebäude,Wohnhaus,31001_1010,None,None,2.0,12065144,None,"MULTIPOLYGON (((382694.352 5837209.612, 382704..."
35283,urn:adv:oid:DEBBAL01000doQvZBL,DEBBAL01000doQvZBL,2026-09-15Z,Gebäude,Wohnhaus,31001_1010,None,None,2.0,12065144,None,"MULTIPOLYGON (((382681.897 5837189.234, 382691..."

## Wärmekatastar

In [37]:
WK_GPKG_PATH = (
    "1_Rohdaten/HN/HN-Gebäudemodell/"
    "HN-Gebäudemodell_04_08_2026/"
    "WK_EG_HN.gpkg"
)

WK_gdf = gpd.read_file(WK_GPKG_PATH)

In [40]:
WK_gdf.columns

Index(['GebaeudeID', 'StrName', 'Hausnummer', 'Stadtteil', 'PLZ', 'Gemeinde',
       'AGS', 'Landkreis', 'Flur', 'Flurstueck', 'Gemarkung', 'GrundFl_qm',
       'BruGeschFl_qm', 'BauAltKl', 'GebTyp', 'NutzungArt', 'AnzlWhg',
       'SolarPot_kwh_a', 'Waermebed_kwh_a', 'ETraeger1', 'ETraeger2',
       'HzngTec1', 'HzngTec2', 'EndEVer_RW_kwh_a', 'EndEVer_kwh_a',
       'CO2_RW_tco2_a', 'CO2_tco2_a', 'Datenqualitaet', 'gemeinde_name',
       'geometry'],
      dtype='object')

In [39]:
WK_gdf

,GebaeudeID,StrName,Hausnummer,Stadtteil,PLZ,Gemeinde,AGS,Landkreis,Flur,Flurstueck,...,ETraeger2,HzngTec1,HzngTec2,EndEVer_RW_kwh_a,EndEVer_kwh_a,CO2_RW_tco2_a,CO2_tco2_a,Datenqualitaet,gemeinde_name,geometry
0,DEBBAL010007CalSBL,Kleiststraße,31,NaN,NaN,Birkenwerder,12065036,Oberhavel,003,295,...,None,Gaskessel,nan,17228.0,17228.0,3.0,3.0,B,Birkenwerder,"POLYGON ((384309.399 5838590.285, 384307.634 5..."
1,DEBBAL010007PVQEBL,Seestraße,13,NaN,NaN,Hohen Neuendorf,12065144,Oberhavel,001,823,...,None,Gaskessel,nan,21752.0,21752.0,4.0,4.0,B,Hohen Neuendorf,"POLYGON ((383697.556 5838473.331, 383706.916 5..."
2,DEBBAL010007Qp5ZBL,Friedrich-Naumann-Straße,60,NaN,NaN,Hohen Neuendorf,12065144,Oberhavel,010,843,...,None,Gaskessel,nan,22598.0,22598.0,5.0,5.0,B,Hohen Neuendorf,"POLYGON ((382644.669 5837230.242, 382655.147 5..."
3,DEBBAL010007RJKYBL,Forstweg,18,NaN,NaN,Hohen Neuendorf,12065144,Oberhavel,002,17,...,None,Gaskessel,nan,33044.0,33044.0,7.0,7.0,B,Hohen Neuendorf,"POLYGON ((386336.047 5838848.282, 386343.988 5..."
4,DEBBAL010007Rof6BL,Eichenallee,27,NaN,NaN,Hohen Neuendorf,12065144,Oberhavel,010,1958,...,None,Gaskessel,none,13310.0,13310.0,3.0,3.0,B,Hohen Neuendorf,"POLYGON ((382730.421 5836867.231, 382739.963 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18260,DEBBAL650004OTibBL,Rheinstraße,70,NaN,NaN,Oranienburg,12065256,Oberhavel,025,160/5,...,None,Gaskessel,nan,9715.0,9715.0,2.0,2.0,B,Oranienburg,"POLYGON ((382039.436 5844450.424, 382039.682 5..."
18261,DEBBAL650004OTisBL,Rheinstraße,77,NaN,NaN,Oranienburg,12065256,Oberhavel,025,155/1,...,Feste_Biomasse,Wärmepumpe (Strom),Kamin (Bestand),6540.0,6540.0,3.0,3.0,B,Oranienburg,"POLYGON ((382081.4 5844441.57, 382074.06 58444..."
18262,DEBBAL650004OTiwBL,Pankeweg,11,NaN,NaN,Oranienburg,12065256,Oberhavel,025,156/11,...,None,Gaskessel,nan,5386.0,5386.0,1.0,1.0,B,Oranienburg,"POLYGON ((382163.68 5844462.39, 382162.83 5844..."
18263,DEBBAL0100098NGwBL,Mühlenbecker Weg,519,NaN,NaN,Hohen Neuendorf,12065144,Oberhavel,005,519,...,None,Sonstiges,None,NaN,8382935.0,NaN,2604.0,C,Hohen Neuendorf,"POLYGON ((383284.204 5844546.361, 383311.736 5..."
18264,DEBBAL01000cqFjnBL,Mühlenbecker Weg,5,NaN,NaN,Oranienburg,12065256,Oberhavel,003,692,...,None,Sonstiges,None,NaN,13134346.0,NaN,3537.0,C,Oranienburg,"POLYGON ((382898.714 5844873.462, 382904.076 5..."

In [42]:
gdf.columns

Index(['GebaeudeID', 'StrName', 'Hausnummer', 'Stadtteil', 'PLZ', 'Gemeinde',
       'AGS', 'Landkreis', 'Flur', 'Flurstueck', 'Gemarkung', 'BauAltKl',
       'GebTyp', 'NutzungArt', 'AnzlWhg', 'SolarPot_k', 'Waermebed_',
       'ETraeger1', 'ETraeger2', 'HzngTec1', 'HzngTec2', 'EndEVer_RW',
       'EndEVer_kw', 'CO2_RW_tco', 'CO2_tco2_a', 'Datenquali', 'gemeinde_n',
       'Etagen', 'funktion', 'heating_carrier', 'Bedarf_katatster', 'Nutzung',
       'Baualter_int', 'komm', 'sector', 'demand_kwh', 'denkmal', 'hoehe_korr',
       'etagen_fin', 'nutzflaeche_korr', 'P_th', 'demand_spec', 'demand_2030',
       'demand_2035', 'demand_2040', 'demand_2045', 'demand_spec_san',
       'geometry'],
      dtype='object')

In [43]:
Alkis_gdf.columns

Index(['identifier', 'oid', 'aktualit', 'gebnutzbez', 'funktion', 'gfkzshh',
       'rellage', 'name', 'anzahlgs', 'gmdschl', 'lagebeztxt', 'geometry'],
      dtype='object')

In [44]:
WK_gdf.columns

Index(['GebaeudeID', 'StrName', 'Hausnummer', 'Stadtteil', 'PLZ', 'Gemeinde',
       'AGS', 'Landkreis', 'Flur', 'Flurstueck', 'Gemarkung', 'GrundFl_qm',
       'BruGeschFl_qm', 'BauAltKl', 'GebTyp', 'NutzungArt', 'AnzlWhg',
       'SolarPot_kwh_a', 'Waermebed_kwh_a', 'ETraeger1', 'ETraeger2',
       'HzngTec1', 'HzngTec2', 'EndEVer_RW_kwh_a', 'EndEVer_kwh_a',
       'CO2_RW_tco2_a', 'CO2_tco2_a', 'Datenqualitaet', 'gemeinde_name',
       'geometry'],
      dtype='object')